### ISSUE TITLE
How can I set strict-math to on in the docpad configuration?

### ISSUE THREAD

**Issue by patrixd** [docpad/docpad-plugin-stylus#15]
Hi

My problem is with the styles with calc. Without set strictMath to true it calculates and changes the style definition when it is compiled.

Example:
```
top: calc(100% - 2em)
```
Changes to:
```
top: calc(98%);
```

I think If I set strictMath to true or on, my problem will be fixed.

I know that I have to add the configuration in plugins, but what property and inside what option object?

**Comment by kizu** [comment]
Which version of the plugin have you used? This issue was fixed a while ago, around Stylus 0.39.0, and the latest version of plugin have now Stylus 0.50.0 where there shouldn't be such issue.

**Comment by kizu** [comment]
Closing due to time passed and no response given.
